### ISSUE TITLE
[Improvement] More post-processing for the category vocabulary

### ISSUE THREAD

**Issue by YipingNUS** [yumeng5/LOTClass#12]
Hi, I really enjoyed reading your paper and the code quality is very impressive as well!

I'm trying to reproduce the experiments on DBpedia dataset. Below is the category vocabulary for the seed word `village`. 

>  Class 8 category vocabulary: ['village', 'villages', 'settlement', 'town', 'east', 'population', 'rural', 'municipality', 'parish', 'na', 'temple', 'pa', 'commune', 'pre', 'ha', 'north', 'hamlet', 'settlements', 'chamber', 'administrative', 'neighbourhood', 'township', 'lies', 'camp', 'locality', 'os', 'villagers', 'iran', 'nest', 'se', 'neighborhood', 'living', 'daily', 'junction', 'palace', 'county', 'crossing', 'south', 'approximately', 'garde', 'market', 'il', 'far', 'reared', 'romanized', 'non', 'west', 'right', 'court', 'wa', 'km', 'hen']

I notice there's still quite a bit of noise like "pa", "il", which I suppose to be state names. Wonder if we had removed those noise, how will the end-to-end text classification accuracy be affected? Some additional filtering that you can consider besides stop words:

1. Filter too short words. Words with 2-3 chars usually are noisy or ambiguous.
2. In my previous work, I kept only nouns for topic classification and adjectives for sentiment classification. There're definitely exceptions but it's a tradeoff between keyword quality and coverage.

**Comment by yumeng5** [comment]
Hi @YipingNUS ,

Thank you for the findings and suggestions! They do make sense and making those modifications may further improve the classification accuracy. 

The filtering criteria can be easily modified here:
https://github.com/yumeng5/LOTClass/blob/20b31813768b102766da54aec57e363815926bab/src/trainer.py#L253

I do appreciate your suggestions but I would like to keep the post-processing as is for now, because this is what I used in my experiments and reported in the paper; changing this part may create difficulties in reproducing the results in the paper. However, please feel free to experiment with whatever settings that work best for your purpose. Please let me know if you find these changes consistently lead to better model performance.

Thanks,
Yu

**Comment by YipingNUS** [comment]
Hi @yumeng5, thanks for your prompt reply! I just managed to reproduce the experiment on dbpedia dataset. I guess the model isn't very sensitive to individual noisy keywords because it uses the "at least 20 keywords match" rule. I think if I change the keyword filtering rules, I might need to tune the threshold also. I will follow your implementation and parameters on a few other datasets then.
