### ISSUE TITLE
Category Vocabulary size in paper is 50, the category vocabulary size created by the algorithm is 70

### ISSUE THREAD

**Issue by leopra** [yumeng5/LOTClass#13]
I was running the code on the AGNews dataset and I noticed the vocabularies size for the 4 classes are:
politics: 70
sports: 69
business: 61
technology: 70
(at least the one printed in the console).
I understand that they are not the same as stopwords and shared words are removed but why is the number higher than 50?

**Comment by yumeng5** [comment]
Hi @leopra ,

The category vocabulary size defaults to `100` (but the actual results can be fewer, like `~70` for the cases you mentioned due to removal of stop words and cross-category words), as mentioned in the second last sentence of Section 3.1:
> "Finally, we form the category vocabulary of each class using the top-100 words ranked by how many times they can replace the label name in the corpus, discarding stopwords and words that appear in multiple categories"

And you could adjust the vocabulary size by setting the following command line argument:
https://github.com/yumeng5/LOTClass/blob/20b31813768b102766da54aec57e363815926bab/src/train.py#L30

Best,
Yu
