### ISSUE TITLE
In w/o self-training baseline, how are the final test predictions made if the [CLS] hasn't be trained？

### ISSUE THREAD

**Issue by ShengdingHu** [yumeng5/LOTClass#15]
Hi! Thanks for presenting such an interesting idea and work. I have a tiny question about the method. For the w/o self-training baseline, will the language model be trained on those documents that contain category words?  If not, the embedding of [CLS] token hasn't been tuned for the classification task, making it hard to predict a test document if the test document doesn't contain category words.

**Comment by yumeng5** [comment]
Hi @ShengdingHu ,

Thanks for the question. Without self-training, the model is indeed only trained on category-indicative tokens and not on [CLS] tokens. However, for the w/o self-training ablation version, we still directly apply the classification linear layer on [CLS] tokens for making the final predictions--even though the [CLS] embeddings are not trained at all. This is probably because there is an implicit regularization effect during token-level training that makes the [CLS] embedding roughly moves towards the token embeddings (i.e., if many token embeddings in a sequence fall in the classification region of topic "sports", so will the [CLS] embedding). This allows us to effectively transfer the knowledge captured via token-level category classification to sequence-level category classification.

I hope my explanation helps. Feel free to let me know if anything remains unclear.

Thanks,
Yu

**Comment by ShengdingHu** [comment]
Thank you for your prompt reply. It's interesting for the knowledge to transfer from token-level to sequence level, which is unexpected at my first glance. Good to see the method works well in practice!
